
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;    // Importing Java Packages to be used in The application
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ztjam
 */
public class MainPage extends javax.swing.JFrame {

    
      byte[] input;
        byte[] keyBytes = "12345678".getBytes();
        byte[] ivBytes = "input123".getBytes();
        SecretKeySpec key = new SecretKeySpec(keyBytes, "DES");
        IvParameterSpec ivSpec = new IvParameterSpec (ivBytes);  // Declaring the variables of MainPage
        Cipher cipher;
        byte[] cipherText;
        int ctLength;
       
       
    /**
     * Creates new form MainPage
     * 
     * 
     * 
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TitleLBL = new javax.swing.JLabel();
        EncryptTF = new javax.swing.JTextField();
        ResultTF = new javax.swing.JTextField();
        DecryptTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EncryptionLBL = new javax.swing.JLabel();
        ResultLBL = new javax.swing.JLabel();
        DecryptionLBL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        InfoLBL = new javax.swing.JLabel();
        imgencrypt = new javax.swing.JTextField();
        ImgEncryptBTN = new javax.swing.JButton();
        ImgDecryptBTN = new javax.swing.JButton();
        stepsLBL1 = new javax.swing.JLabel();
        stepsLBL2 = new javax.swing.JLabel();
        stepsLBL3 = new javax.swing.JLabel();
        stepsLBL4 = new javax.swing.JLabel();
        stepsLBL5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLBL.setText("Text Encryption");

        EncryptTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncryptTFActionPerformed(evt);
            }
        });

        jButton1.setText("Encrypt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Decrypt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        EncryptionLBL.setText("Normal Text");

        ResultLBL.setText("Encrypted");

        DecryptionLBL.setText("Decrypted");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(EncryptTF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(ResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(DecryptTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jButton1)
                .addGap(200, 200, 200)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(TitleLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(EncryptionLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResultLBL)
                        .addGap(180, 180, 180)))
                .addComponent(DecryptionLBL)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(TitleLBL)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncryptionLBL)
                    .addComponent(ResultLBL)
                    .addComponent(DecryptionLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncryptTF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DecryptTF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(49, 49, 49))
        );

        DecryptTF.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Text Encryption", jPanel1);

        InfoLBL.setText("Enter digits to create a key to encrypt or decrypt the puppy image");

        imgencrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgencryptActionPerformed(evt);
            }
        });

        ImgEncryptBTN.setText("Encrypt Image");
        ImgEncryptBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImgEncryptBTNActionPerformed(evt);
            }
        });

        ImgDecryptBTN.setText("Decrypt Image");
        ImgDecryptBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImgDecryptBTNActionPerformed(evt);
            }
        });

        stepsLBL1.setText("1. Open puppy image in source folder");

        stepsLBL2.setText("2. Enter a key to encrypt the image with");

        stepsLBL3.setText("3, Press Encrypt image and view puppy image again");

        stepsLBL4.setText("4. Enter key to decrypt image");

        stepsLBL5.setText("5. Press Decrypt image and view puppy image again");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(imgencrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ImgEncryptBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ImgDecryptBTN))
                            .addComponent(InfoLBL)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stepsLBL2)
                            .addComponent(stepsLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stepsLBL3)
                            .addComponent(stepsLBL4)
                            .addComponent(stepsLBL5))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(stepsLBL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stepsLBL2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stepsLBL3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stepsLBL4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stepsLBL5)
                .addGap(82, 82, 82)
                .addComponent(InfoLBL)
                .addGap(18, 18, 18)
                .addComponent(imgencrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImgEncryptBTN)
                    .addComponent(ImgDecryptBTN))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Image Encryption", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EncryptTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncryptTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EncryptTFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
        cipher.init(Cipher.DECRYPT_MODE,key,ivSpec); // Intitialising the Decrypt mode using the established secret key
        
        byte[] plainText = new byte [cipher.getOutputSize(ctLength)]; //  Creating new byte called Plain Text using the length variable
        
        int ptLength = cipher.update (cipherText, 0, ctLength, plainText, 0); // Updating the cipher
        
        ptLength += cipher.doFinal(plainText,ptLength);// 
        DecryptTF.setText(new String(plainText)); //   // Set the Decrypt text field to the plain text cipher text string
        
        } catch(Exception e){ // Catch any exceptions caused
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        input = EncryptTF.getText().getBytes();  // Get the text of the text field EncryptTF
           SecretKeySpec key = new SecretKeySpec(keyBytes, "DES");  // Creating a Key that will be used later in the cipher
           IvParameterSpec ivSpec = new IvParameterSpec(ivBytes);
           cipher = Cipher.getInstance("DES/CTR/NoPadding"); // Declaring what kind of cipher is to be used
           cipher.init(Cipher.ENCRYPT_MODE,key,ivSpec); // Intitialising the encrypt mode using the established secret key
           cipherText = new byte[cipher.getOutputSize(input.length)]; //Declaring the byte for cipher text with how long the input is
           ctLength = cipher.update(input, 0,input.length, cipherText, 0);  // Declaring the ct Lenght
           
           ctLength += cipher.doFinal(cipherText, ctLength); // Calling the cihpher to encrypt CipherText using ctLenth
           ResultTF.setText(new String(cipherText)); // Set the result text field to the encrypted cipher text string
        } catch(Exception e){ // Catch any exceptions caused
            
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void imgencryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgencryptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgencryptActionPerformed

    private void ImgEncryptBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImgEncryptBTNActionPerformed
       try {
            int key = Integer.parseInt(imgencrypt.getText());
            FileInputStream fis = new FileInputStream("pup.jpg");
            byte data[] = new byte[fis.available()]; //Converting the image into a byte array
            fis.read(data);
            int i = 0;
            for (byte b : data) {
                data[i] = (byte) (b ^ key); //XOR operation on each byte array to the value of the image
                i++;
            }
            FileOutputStream fos = new FileOutputStream("pup.jpg");
            fos.write(data); //New byte array to be encrypted
            fos.close();
            fis.close();
            JOptionPane.showMessageDialog(null, "Encryption Done...");
        } catch (Exception e) {
            e.printStackTrace();
        }                              
    }//GEN-LAST:event_ImgEncryptBTNActionPerformed

    private void ImgDecryptBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImgDecryptBTNActionPerformed
        try {

            int key = Integer.parseInt(imgencrypt.getText());
            FileInputStream fis = new FileInputStream("pup.jpg"); //This is choosing the puppy image to be decryped, free to use whatever image and rename it
            byte data[] = new byte[fis.available()]; //This is the image being converted into a byte array
            fis.read(data); //This is to read the array data
            int i = 0;
            for (byte b : data) {
                data[i] = (byte) (b ^ key); //This is a XOR operation so that each byte can be decrypted
                i++;
            }
            FileOutputStream fos = new FileOutputStream("pup.jpg");
            fos.write(data);        //This is writing to the decrypted image
            fos.close();
            fis.close();
            JOptionPane.showMessageDialog(null, "Decryption Done...");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ImgDecryptBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true); // seting the page to be visible if it was run seperatly
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DecryptTF;
    private javax.swing.JLabel DecryptionLBL;
    private javax.swing.JTextField EncryptTF;
    private javax.swing.JLabel EncryptionLBL;
    private javax.swing.JButton ImgDecryptBTN;
    private javax.swing.JButton ImgEncryptBTN;
    private javax.swing.JLabel InfoLBL;
    private javax.swing.JLabel ResultLBL;
    private javax.swing.JTextField ResultTF;
    private javax.swing.JLabel TitleLBL;
    private javax.swing.JTextField imgencrypt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel stepsLBL1;
    private javax.swing.JLabel stepsLBL2;
    private javax.swing.JLabel stepsLBL3;
    private javax.swing.JLabel stepsLBL4;
    private javax.swing.JLabel stepsLBL5;
    // End of variables declaration//GEN-END:variables
}
